spring.application.name=springio25-demo
spring.profiles.active=secrets

github.org=rwinch
github.repo=spring-framework

logging.level.root=WARN
logging.level.demo=INFO
logging.pattern.console=%clr(%c{1}){cyan} : %m%n

# DevTools and Thymeleaf auto-reload configuration
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true