spring.application.name=springio25-demo
spring.profiles.active=secrets

github.org=spring-projects
github.repo=spring-framework

spring.http.client.service.group.github.base-url=https://api.github.com
spring.http.client.service.group.github.default-headers.accept=application/vnd.github.v3+json
spring.http.client.service.group.stackoverflow.base-url=https://api.stackexchange.com?site=stackoverflow

logging.level.demo=INFO

spring.security.oauth2.client.registration.github.scope=user:email
